Create story
Sayed94h/Hear-My-Story pull request #22
Opened 2021-01-07 18:34 UTC by Eltayeb-Elgaali

closes #7

2021-01-07 18:49 UTC, Toinne requested changes

2021-01-07 18:49 UTC, Toinne commented on client/.eslintcache
> +[{"/home/hackyourfuture/Downloads/hack-my-future/Hear-My-Story/client/src/index.js":"1","/home/hackyourfuture/Downloads/hack-my-future/Hear-My-Story/client/src/App.js":"2","/home/hackyourfuture/Downl
Would remove this file should not be committed
https://github.com/Sayed94h/Hear-My-Story/pull/21/files Sayed added it to be ignored in the build fix PR

2021-01-07 18:49 UTC, Toinne commented on api/controllers/stories.js
> +    if(!req.body.story) return res.status(400).send('No text provided');
Requirement: can you make sure the error follow the pattern of the other errors ?
```suggestion
    if (!req.body.story) {
       return res.status(400).send({error: true, message: "No story submitted"});
    }
```

2021-01-07 18:49 UTC, Toinne commented on api/controllers/stories.js
> +            console.log(story);
Requirement: remove me

2021-01-07 20:15 UTC, abelRoland reviewed
Together with what @Toinne told, I have just some other small comments. Thanks for the work @Eltayeb-Elgaali

2021-01-07 20:15 UTC, abelRoland commented on api/models/Story.js
>  const StorySchema = new mongoose.Schema({
Here it's also possible to use the variable `Schema` ;)

2021-01-07 20:15 UTC, abelRoland commented on client/.eslintcache
> +[{"/home/hackyourfuture/Downloads/hack-my-future/Hear-My-Story/client/src/index.js":"1","/home/hackyourfuture/Downloads/hack-my-future/Hear-My-Story/client/src/App.js":"2","/home/hackyourfuture/Downl
Is this file needed?

2021-01-10 10:00 UTC, Sayed94h commented on client/.eslintcache
> +[{"/home/hackyourfuture/Downloads/hack-my-future/Hear-My-Story/client/src/index.js":"1","/home/hackyourfuture/Downloads/hack-my-future/Hear-My-Story/client/src/App.js":"2","/home/hackyourfuture/Downl
If you mean "the file .eslintcache", then I don't think that it is needed. I searched a lot to get rid of it but got nothing. That is why I added it in .gitignore file in the previous PR.

2021-01-10 10:07 UTC, Sayed94h reviewed
@Eltayeb-Elgaali 

Can you remove all the prefixes "cross-env" from [here](https://github.com/Sayed94h/Hear-My-Story/blob/main/client/package.json) and also this `"devDependencies": { "cross-env": "^7.0.3"	}` from the same file? because it caused failure in the deployment of our app on Heroku otherwise I will do that in a separate PR.
Thanks

2021-01-10 11:35 UTC, Toinne commented on api/controllers/stories.js
> +            console.log(story);
```suggestion
```

2021-01-12 19:57 UTC, Toinne approved these changes

2021-01-12 19:58 UTC, merged