Adding User routes
Sayed94h/Hear-My-Story pull request #29
Opened 2021-01-14 09:58 UTC by abelRoland

This closes #23  and this closes #24

2021-01-14 19:11 UTC, Eltayeb-Elgaali reviewed
It seems good to me.
the only thing is the route that should be may be changed.

2021-01-14 19:17 UTC, Toinne requested changes

2021-01-14 19:17 UTC, Toinne commented on api/routes/user.js
> +router.put(
Requirement: make the route `/user`

2021-01-15 13:10 UTC, Sayed94h approved these changes
Now it is how we discussed in our previous meeting so I am going to approve it.

2021-01-15 14:04 UTC, HazemBittar approved these changes

2021-01-16 16:22 UTC, Toinne commented on api/routes/user.js
> +app.put('/users/:id/update', auth, updateUser);
@abelRoland it is very important to authenticate these routes with auth!! If not this endpoint is public for the entire internet.

2021-01-16 16:22 UTC, Toinne commented on api/routes/user.js
> +    if (req.user._id != id) {
@abelRoland you only want to allow updating your own user account. If you don't add this anyone on the internet can update the details of the user including password.

2021-01-16 16:22 UTC, Toinne commented on api/server.js
> +app.use('/', require('./routes/user.js'));
This should have been added @abelRoland

2021-01-16 16:24 UTC, merged